In [1]:
import pandas as pd
import numpy as np

In [2]:
import optuna
import tensorflow as tf

""" Sequential -  It allows you to create a model by simply adding layers one after another.
This is used for building simple neural networks where the flow of data is straightforward, 
from input to output, through a series of layers."""
from tensorflow.keras.models import Sequential

"""Dense is a fully connected layer, also known as a dense layer, in a neural network.
Each neuron in a dense layer receives input from all neurons in the previous layer."""
from tensorflow.keras.layers import Dense

"""Optimizers computes adaptive learning rates for each parameter"""
from tensorflow.keras.optimizers import SGD, Adam, RMSprop, Adagrad, Adadelta, Nadam


from sklearn.metrics import roc_auc_score

In [3]:
data = pd.read_csv('churn_modelling.csv')

data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
data.describe(include='all')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5000.50000,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [5]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [7]:
data = pd.get_dummies(data, drop_first=True)

data

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [8]:
targets = data['Exited']

inputs = data.drop(['Exited'],axis=1)

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(inputs)

scaled = scaler.transform(inputs)

inputs_scaled = pd.DataFrame(scaled, columns=inputs.columns)

inputs_scaled

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,-0.578736,-0.573809,-1.095988
1,-0.440036,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.578736,1.742740,-1.095988
2,-1.536794,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,-0.578736,-0.573809,-1.095988
3,0.501521,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.578736,-0.573809,-1.095988
4,2.063884,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.578736,1.742740,-1.095988
...,...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419,-0.578736,-0.573809,0.912419
9996,-1.391939,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988,-0.578736,-0.573809,0.912419
9997,0.604988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643,-0.578736,-0.573809,-1.095988
9998,1.256835,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231,1.727904,-0.573809,0.912419
9999,1.463771,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370,-0.578736,-0.573809,-1.095988

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs_scaled, targets, test_size=0.2, random_state=42)

## ANN model

In [13]:
def create_model(trial):
    # Building artificial neural network
    model = Sequential()

     # we add 2 hidden layers and 1 output layer
    model.add(Dense(units=trial.suggest_int('units_layer1', 6, 32), activation='relu'))
    model.add(Dense(units=trial.suggest_int('units_layer2', 6, 32), activation='relu'))
    model.add(Dense(units=1, activation='sigmoid'))

    # Suggest hyperparameters for the optimizer
    optimizer_name = trial.suggest_categorical('optimizer', ['adam', 'sgd', 'rmsprop', 'adagrad'])
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
    
    if optimizer_name == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        optimizer = SGD(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    elif optimizer_name == 'adagrad':
        optimizer = Adagrad(learning_rate=learning_rate)
    
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['AUC'])
    
    return model

## Optimize hyperparameters with Optuna

In [14]:
def optimal(trial):
    
    # Suggest the number of epochs and batch size
    epochs = trial.suggest_int('epochs', 10, 50)
    batch_size = trial.suggest_int('batch_size', 16, 64)
    
    model = create_model(trial)
    
    history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)
    
    y_pred = model.predict(X_test)
    auc = roc_auc_score(y_test, y_pred)
    
    return auc

study = optuna.create_study(direction='maximize')
study.optimize(optimal, n_trials=10)

print(f"Best trial: {study.best_trial.value}")
print(f"Best hyperparameters: {study.best_trial.params}")

[I 2024-12-16 22:56:49,191] A new study created in memory with name: no-name-383c2817-4b8e-44a5-8f91-61d6ed64bfa3
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adagrad` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adagrad`.

Epoch 1/48
146/146 [==============================] - 0s 390us/step - loss: 0.6547 - auc: 0.4662
Epoch 2/48
146/146 [==============================] - 0s 325us/step - loss: 0.6041 - auc: 0.4772
Epoch 3/48
146/146 [==============================] - 0s 328us/step - loss: 0.5763 - auc: 0.4950
Epoch 4/48
146/146 [==============================] - 0s 335us/step - loss: 0.5576 - auc: 0.5150
Epoch 5/48
146/146 [==============================] - 0s 335us/step - loss: 0.5440 - auc: 0.5313
Epoch 6/48
146/146 [==============================] - 0s 329us/step - loss: 0.5333 - auc: 0.5492
Epoch 7/48
146/146 [==============================] - 0s 324us/step - loss: 0.5246 - auc: 0.5663
Epoch 8/48
146/146 [==============================] - 0s 331us/step - loss: 0.5172 - auc: 0.5808
Epoch 9/48
146/146 [==============================] - 0s 330us/step - loss: 0.5108 - auc: 0.5957
Epoch 10/48
146/146 [==============================] - 0s 329us/step - loss: 0.5051 - auc: 0.6092
Epoch 11/48
146/146 [==============================] - 0s 319us/step - loss: 0.5001 - auc: 0.6218
Epoch 12/48
146/146 [==============================] - 0s 332us/step - loss: 0.4955 - auc: 0.6340
Epoch 13/48
146/146 [==============================] - 0s 320us/step - loss: 0.4913 - auc: 0.6444
Epoch 14/48
146/146 [==============================] - 0s 359us/step - loss: 0.4875 - auc: 0.6544
Epoch 15/48
146/146 [==============================] - 0s 426us/step - loss: 0.4839 - auc: 0.6629
Epoch 16/48
146/146 [==============================] - 0s 320us/step - loss: 0.4807 - auc: 0.6719
Epoch 17/48
146/146 [==============================] - 0s 321us/step - loss: 0.4776 - auc: 0.6798
Epoch 18/48
146/146 [==============================] - 0s 330us/step - loss: 0.4747 - auc: 0.6870
Epoch 19/48
146/146 [==============================] - 0s 326us/step - loss: 0.4720 - auc: 0.6931
Epoch 20/48
146/146 [==============================] - 0s 322us/step - loss: 0.4695 - auc: 0.6995
Epoch 21/48
146/146 [==============================] - 0s 330us/step - loss: 0.4672 - auc: 0.7050
Epoch 22/48
146/146 [==============================] - 0s 337us/step - loss: 0.4649 - auc: 0.7099
Epoch 23/48
146/146 [==============================] - 0s 318us/step - loss: 0.4628 - auc: 0.7149
Epoch 24/48
146/146 [==============================] - 0s 333us/step - loss: 0.4608 - auc: 0.7192
Epoch 25/48
146/146 [==============================] - 0s 338us/step - loss: 0.4589 - auc: 0.7232
Epoch 26/48
146/146 [==============================] - 0s 333us/step - loss: 0.4571 - auc: 0.7266
Epoch 27/48
146/146 [==============================] - 0s 333us/step - loss: 0.4554 - auc: 0.7306
Epoch 28/48
146/146 [==============================] - 0s 336us/step - loss: 0.4538 - auc: 0.7336
Epoch 29/48
146/146 [==============================] - 0s 337us/step - loss: 0.4522 - auc: 0.7363
Epoch 30/48
146/146 [==============================] - 0s 390us/step - loss: 0.4507 - auc: 0.7394
Epoch 31/48
146/146 [==============================] - 0s 343us/step - loss: 0.4493 - auc: 0.7419
Epoch 32/48
146/146 [==============================] - 0s 327us/step - loss: 0.4479 - auc: 0.7443
Epoch 33/48
146/146 [==============================] - 0s 326us/step - loss: 0.4466 - auc: 0.7468
Epoch 34/48
146/146 [==============================] - 0s 335us/step - loss: 0.4454 - auc: 0.7488
Epoch 35/48
146/146 [==============================] - 0s 333us/step - loss: 0.4442 - auc: 0.7506
Epoch 36/48
146/146 [==============================] - 0s 360us/step - loss: 0.4430 - auc: 0.7524
Epoch 37/48
146/146 [==============================] - 0s 350us/step - loss: 0.4419 - auc: 0.7542
Epoch 38/48
146/146 [==============================] - 0s 360us/step - loss: 0.4408 - auc: 0.7559
Epoch 39/48
146/146 [==============================] - 0s 360us/step - loss: 0.4398 - auc: 0.7573
Epoch 40/48
146/146 [==============================] - 0s 366us/step - loss: 0.4388 - auc: 0.7587
Epoch 41/48
146/146 [==============================] - 0s 329us/step - loss: 0.4379 - auc: 0.7602
Epoch 42/48
146/146 [==============================] - 0s 339us/step - loss: 0.4370 - auc: 0.7616
Epoch 43/48
146/146 [==============================] - 0s 347us/step - loss: 0.4361 - auc: 0.7627
Epoch 44/48
146/146 [==============================] - 0s 357us/step - loss: 0.4352 - auc: 0.7637
Epoch 45/48
146/146 [==============================] - 0s 348us/step - loss: 0.4344 - auc: 0.7649
Epoch 46/48
146/146 [==============================] - 0s 333us/step - loss: 0.4336 - auc: 0.7661
Epoch 47/48
146/146 [==============================] - 0s 340us/step - loss: 0.4329 - auc: 0.7670
Epoch 48/48
146/146 [==============================] - 0s 362us/step - loss: 0.4321 - auc: 0.7680
63/63 [==============================] - 0s 290us/step

[I 2024-12-16 22:56:52,047] Trial 0 finished with value: 0.785681599744122 and parameters: {'epochs': 48, 'batch_size': 55, 'units_layer1': 29, 'units_layer2': 15, 'optimizer': 'adagrad', 'learning_rate': 0.0012843568508620919}. Best is trial 0 with value: 0.785681599744122.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adagrad` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adagrad`.

Epoch 1/26
308/308 [==============================] - 0s 378us/step - loss: 0.9973 - auc: 0.4906
Epoch 2/26
308/308 [==============================] - 0s 302us/step - loss: 0.9646 - auc: 0.4888
Epoch 3/26
308/308 [==============================] - 0s 299us/step - loss: 0.9433 - auc: 0.4872
Epoch 4/26
308/308 [==============================] - 0s 300us/step - loss: 0.9266 - auc: 0.4854
Epoch 5/26
308/308 [==============================] - 0s 294us/step - loss: 0.9126 - auc: 0.4843
Epoch 6/26
308/308 [==============================] - 0s 288us/step - loss: 0.9004 - auc: 0.4829
Epoch 7/26
308/308 [==============================] - 0s 302us/step - loss: 0.8895 - auc: 0.4819
Epoch 8/26
308/308 [==============================] - 0s 289us/step - loss: 0.8797 - auc: 0.4811
Epoch 9/26
308/308 [==============================] - 0s 331us/step - loss: 0.8707 - auc: 0.4806
Epoch 10/26
308/308 [==============================] - 0s 340us/step - loss: 0.8624 - auc: 0.4801
Epoch 11/26
308/308 [==============================] - 0s 329us/step - loss: 0.8547 - auc: 0.4789
Epoch 12/26
308/308 [==============================] - 0s 324us/step - loss: 0.8475 - auc: 0.4782
Epoch 13/26
308/308 [==============================] - 0s 312us/step - loss: 0.8407 - auc: 0.4775
Epoch 14/26
308/308 [==============================] - 0s 323us/step - loss: 0.8343 - auc: 0.4771
Epoch 15/26
308/308 [==============================] - 0s 324us/step - loss: 0.8283 - auc: 0.4763
Epoch 16/26
308/308 [==============================] - 0s 328us/step - loss: 0.8225 - auc: 0.4759
Epoch 17/26
308/308 [==============================] - 0s 337us/step - loss: 0.8171 - auc: 0.4752
Epoch 18/26
308/308 [==============================] - 0s 344us/step - loss: 0.8118 - auc: 0.4747
Epoch 19/26
308/308 [==============================] - 0s 346us/step - loss: 0.8068 - auc: 0.4745
Epoch 20/26
308/308 [==============================] - 0s 353us/step - loss: 0.8020 - auc: 0.4737
Epoch 21/26
308/308 [==============================] - 0s 348us/step - loss: 0.7974 - auc: 0.4741
Epoch 22/26
308/308 [==============================] - 0s 346us/step - loss: 0.7930 - auc: 0.4732
Epoch 23/26
308/308 [==============================] - 0s 336us/step - loss: 0.7887 - auc: 0.4731
Epoch 24/26
308/308 [==============================] - 0s 325us/step - loss: 0.7846 - auc: 0.4728
Epoch 25/26
308/308 [==============================] - 0s 315us/step - loss: 0.7806 - auc: 0.4727
Epoch 26/26
308/308 [==============================] - 0s 316us/step - loss: 0.7767 - auc: 0.4719
63/63 [==============================] - 0s 279us/step

[I 2024-12-16 22:56:54,919] Trial 1 finished with value: 0.48624259956836424 and parameters: {'epochs': 26, 'batch_size': 26, 'units_layer1': 15, 'units_layer2': 21, 'optimizer': 'adagrad', 'learning_rate': 0.0001832527149256269}. Best is trial 0 with value: 0.785681599744122.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.RMSprop` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.RMSprop`.

Epoch 1/25
229/229 [==============================] - 0s 404us/step - loss: 0.4464 - auc: 0.7405
Epoch 2/25
229/229 [==============================] - 0s 364us/step - loss: 0.3689 - auc: 0.8350
Epoch 3/25
229/229 [==============================] - 0s 350us/step - loss: 0.3503 - auc: 0.8519
Epoch 4/25
229/229 [==============================] - 0s 338us/step - loss: 0.3423 - auc: 0.8590
Epoch 5/25
229/229 [==============================] - 0s 343us/step - loss: 0.3379 - auc: 0.8629
Epoch 6/25
229/229 [==============================] - 0s 333us/step - loss: 0.3348 - auc: 0.8652
Epoch 7/25
229/229 [==============================] - 0s 324us/step - loss: 0.3332 - auc: 0.8678
Epoch 8/25
229/229 [==============================] - 0s 325us/step - loss: 0.3318 - auc: 0.8691
Epoch 9/25
229/229 [==============================] - 0s 324us/step - loss: 0.3314 - auc: 0.8692
Epoch 10/25
229/229 [==============================] - 0s 321us/step - loss: 0.3305 - auc: 0.8700
Epoch 11/25
229/229 [==============================] - 0s 355us/step - loss: 0.3275 - auc: 0.8720
Epoch 12/25
229/229 [==============================] - 0s 316us/step - loss: 0.3268 - auc: 0.8739
Epoch 13/25
229/229 [==============================] - 0s 323us/step - loss: 0.3258 - auc: 0.8741
Epoch 14/25
229/229 [==============================] - 0s 327us/step - loss: 0.3243 - auc: 0.8741
Epoch 15/25
229/229 [==============================] - 0s 328us/step - loss: 0.3238 - auc: 0.8756
Epoch 16/25
229/229 [==============================] - 0s 328us/step - loss: 0.3212 - auc: 0.8780
Epoch 17/25
229/229 [==============================] - 0s 318us/step - loss: 0.3225 - auc: 0.8759
Epoch 18/25
229/229 [==============================] - 0s 317us/step - loss: 0.3203 - auc: 0.8787
Epoch 19/25
229/229 [==============================] - 0s 316us/step - loss: 0.3189 - auc: 0.8798
Epoch 20/25
229/229 [==============================] - 0s 354us/step - loss: 0.3179 - auc: 0.8805
Epoch 21/25
229/229 [==============================] - 0s 343us/step - loss: 0.3176 - auc: 0.8813
Epoch 22/25
229/229 [==============================] - 0s 355us/step - loss: 0.3171 - auc: 0.8811
Epoch 23/25
229/229 [==============================] - 0s 356us/step - loss: 0.3161 - auc: 0.8817
Epoch 24/25
229/229 [==============================] - 0s 338us/step - loss: 0.3144 - auc: 0.8822
Epoch 25/25
229/229 [==============================] - 0s 335us/step - loss: 0.3143 - auc: 0.8837
63/63 [==============================] - 0s 296us/step

[I 2024-12-16 22:56:57,138] Trial 2 finished with value: 0.8592971905673493 and parameters: {'epochs': 25, 'batch_size': 35, 'units_layer1': 30, 'units_layer2': 18, 'optimizer': 'rmsprop', 'learning_rate': 0.002746317704472586}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adagrad` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adagrad`.

Epoch 1/41
154/154 [==============================] - 0s 390us/step - loss: 0.6834 - auc: 0.5234
Epoch 2/41
154/154 [==============================] - 0s 312us/step - loss: 0.6801 - auc: 0.5228
Epoch 3/41
154/154 [==============================] - 0s 318us/step - loss: 0.6777 - auc: 0.5210
Epoch 4/41
154/154 [==============================] - 0s 314us/step - loss: 0.6757 - auc: 0.5203
Epoch 5/41
154/154 [==============================] - 0s 314us/step - loss: 0.6739 - auc: 0.5203
Epoch 6/41
154/154 [==============================] - 0s 310us/step - loss: 0.6723 - auc: 0.5195
Epoch 7/41
154/154 [==============================] - 0s 310us/step - loss: 0.6708 - auc: 0.5189
Epoch 8/41
154/154 [==============================] - 0s 312us/step - loss: 0.6694 - auc: 0.5184
Epoch 9/41
154/154 [==============================] - 0s 315us/step - loss: 0.6682 - auc: 0.5177
Epoch 10/41
154/154 [==============================] - 0s 313us/step - loss: 0.6670 - auc: 0.5172
Epoch 11/41
154/154 [==============================] - 0s 310us/step - loss: 0.6658 - auc: 0.5170
Epoch 12/41
154/154 [==============================] - 0s 313us/step - loss: 0.6648 - auc: 0.5165
Epoch 13/41
154/154 [==============================] - 0s 325us/step - loss: 0.6638 - auc: 0.5164
Epoch 14/41
154/154 [==============================] - 0s 320us/step - loss: 0.6628 - auc: 0.5161
Epoch 15/41
154/154 [==============================] - 0s 314us/step - loss: 0.6618 - auc: 0.5155
Epoch 16/41
154/154 [==============================] - 0s 325us/step - loss: 0.6609 - auc: 0.5152
Epoch 17/41
154/154 [==============================] - 0s 318us/step - loss: 0.6601 - auc: 0.5149
Epoch 18/41
154/154 [==============================] - 0s 324us/step - loss: 0.6592 - auc: 0.5143
Epoch 19/41
154/154 [==============================] - 0s 318us/step - loss: 0.6584 - auc: 0.5141
Epoch 20/41
154/154 [==============================] - 0s 322us/step - loss: 0.6576 - auc: 0.5139
Epoch 21/41
154/154 [==============================] - 0s 320us/step - loss: 0.6568 - auc: 0.5137
Epoch 22/41
154/154 [==============================] - 0s 316us/step - loss: 0.6561 - auc: 0.5135
Epoch 23/41
154/154 [==============================] - 0s 311us/step - loss: 0.6554 - auc: 0.5132
Epoch 24/41
154/154 [==============================] - 0s 310us/step - loss: 0.6547 - auc: 0.5131
Epoch 25/41
154/154 [==============================] - 0s 305us/step - loss: 0.6540 - auc: 0.5131
Epoch 26/41
154/154 [==============================] - 0s 296us/step - loss: 0.6533 - auc: 0.5128
Epoch 27/41
154/154 [==============================] - 0s 304us/step - loss: 0.6526 - auc: 0.5124
Epoch 28/41
154/154 [==============================] - 0s 312us/step - loss: 0.6520 - auc: 0.5120
Epoch 29/41
154/154 [==============================] - 0s 314us/step - loss: 0.6514 - auc: 0.5119
Epoch 30/41
154/154 [==============================] - 0s 307us/step - loss: 0.6508 - auc: 0.5118
Epoch 31/41
154/154 [==============================] - 0s 319us/step - loss: 0.6502 - auc: 0.5117
Epoch 32/41
154/154 [==============================] - 0s 320us/step - loss: 0.6496 - auc: 0.5114
Epoch 33/41
154/154 [==============================] - 0s 315us/step - loss: 0.6490 - auc: 0.5112
Epoch 34/41
154/154 [==============================] - 0s 391us/step - loss: 0.6484 - auc: 0.5110
Epoch 35/41
154/154 [==============================] - 0s 344us/step - loss: 0.6479 - auc: 0.5109
Epoch 36/41
154/154 [==============================] - 0s 352us/step - loss: 0.6473 - auc: 0.5109
Epoch 37/41
154/154 [==============================] - 0s 315us/step - loss: 0.6468 - auc: 0.5106
Epoch 38/41
154/154 [==============================] - 0s 307us/step - loss: 0.6463 - auc: 0.5101
Epoch 39/41
154/154 [==============================] - 0s 313us/step - loss: 0.6457 - auc: 0.5100
Epoch 40/41
154/154 [==============================] - 0s 306us/step - loss: 0.6452 - auc: 0.5101
Epoch 41/41
154/154 [==============================] - 0s 302us/step - loss: 0.6447 - auc: 0.5100
63/63 [==============================] - 0s 277us/step

[I 2024-12-16 22:56:59,525] Trial 3 finished with value: 0.5048095878242612 and parameters: {'epochs': 41, 'batch_size': 52, 'units_layer1': 20, 'units_layer2': 10, 'optimizer': 'adagrad', 'learning_rate': 7.458567986266206e-05}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.RMSprop` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.RMSprop`.

Epoch 1/20
134/134 [==============================] - 0s 404us/step - loss: 0.4317 - auc: 0.7626
Epoch 2/20
134/134 [==============================] - 0s 333us/step - loss: 0.3652 - auc: 0.8376
Epoch 3/20
134/134 [==============================] - 0s 336us/step - loss: 0.3448 - auc: 0.8566
Epoch 4/20
134/134 [==============================] - 0s 335us/step - loss: 0.3418 - auc: 0.8598
Epoch 5/20
134/134 [==============================] - 0s 322us/step - loss: 0.3379 - auc: 0.8626
Epoch 6/20
134/134 [==============================] - 0s 320us/step - loss: 0.3351 - auc: 0.8660
Epoch 7/20
134/134 [==============================] - 0s 323us/step - loss: 0.3334 - auc: 0.8674
Epoch 8/20
134/134 [==============================] - 0s 326us/step - loss: 0.3326 - auc: 0.8680
Epoch 9/20
134/134 [==============================] - 0s 321us/step - loss: 0.3318 - auc: 0.8675
Epoch 10/20
134/134 [==============================] - 0s 323us/step - loss: 0.3299 - auc: 0.8702
Epoch 11/20
134/134 [==============================] - 0s 317us/step - loss: 0.3293 - auc: 0.8716
Epoch 12/20
134/134 [==============================] - 0s 322us/step - loss: 0.3279 - auc: 0.8731
Epoch 13/20
134/134 [==============================] - 0s 325us/step - loss: 0.3281 - auc: 0.8727
Epoch 14/20
134/134 [==============================] - 0s 314us/step - loss: 0.3275 - auc: 0.8734
Epoch 15/20
134/134 [==============================] - 0s 329us/step - loss: 0.3256 - auc: 0.8742
Epoch 16/20
134/134 [==============================] - 0s 320us/step - loss: 0.3261 - auc: 0.8736
Epoch 17/20
134/134 [==============================] - 0s 323us/step - loss: 0.3256 - auc: 0.8749
Epoch 18/20
134/134 [==============================] - 0s 321us/step - loss: 0.3246 - auc: 0.8755
Epoch 19/20
134/134 [==============================] - 0s 317us/step - loss: 0.3226 - auc: 0.8784
Epoch 20/20
134/134 [==============================] - 0s 314us/step - loss: 0.3225 - auc: 0.8776
63/63 [==============================] - 0s 273us/step

[I 2024-12-16 22:57:00,658] Trial 4 finished with value: 0.8465713774501188 and parameters: {'epochs': 20, 'batch_size': 60, 'units_layer1': 22, 'units_layer2': 10, 'optimizer': 'rmsprop', 'learning_rate': 0.006521075660828948}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.

Epoch 1/25
229/229 [==============================] - 0s 334us/step - loss: 0.5435 - auc: 0.5470
Epoch 2/25
229/229 [==============================] - 0s 291us/step - loss: 0.5425 - auc: 0.5482
Epoch 3/25
229/229 [==============================] - 0s 289us/step - loss: 0.5414 - auc: 0.5492
Epoch 4/25
229/229 [==============================] - 0s 287us/step - loss: 0.5404 - auc: 0.5504
Epoch 5/25
229/229 [==============================] - 0s 288us/step - loss: 0.5394 - auc: 0.5515
Epoch 6/25
229/229 [==============================] - 0s 283us/step - loss: 0.5385 - auc: 0.5527
Epoch 7/25
229/229 [==============================] - 0s 289us/step - loss: 0.5375 - auc: 0.5539
Epoch 8/25
229/229 [==============================] - 0s 292us/step - loss: 0.5366 - auc: 0.5550
Epoch 9/25
229/229 [==============================] - 0s 300us/step - loss: 0.5357 - auc: 0.5563
Epoch 10/25
229/229 [==============================] - 0s 300us/step - loss: 0.5348 - auc: 0.5572
Epoch 11/25
229/229 [==============================] - 0s 332us/step - loss: 0.5339 - auc: 0.5583
Epoch 12/25
229/229 [==============================] - 0s 294us/step - loss: 0.5331 - auc: 0.5596
Epoch 13/25
229/229 [==============================] - 0s 301us/step - loss: 0.5323 - auc: 0.5607
Epoch 14/25
229/229 [==============================] - 0s 314us/step - loss: 0.5314 - auc: 0.5618
Epoch 15/25
229/229 [==============================] - 0s 307us/step - loss: 0.5307 - auc: 0.5627
Epoch 16/25
229/229 [==============================] - 0s 285us/step - loss: 0.5299 - auc: 0.5637
Epoch 17/25
229/229 [==============================] - 0s 302us/step - loss: 0.5291 - auc: 0.5649
Epoch 18/25
229/229 [==============================] - 0s 304us/step - loss: 0.5284 - auc: 0.5662
Epoch 19/25
229/229 [==============================] - 0s 289us/step - loss: 0.5276 - auc: 0.5670
Epoch 20/25
229/229 [==============================] - 0s 331us/step - loss: 0.5269 - auc: 0.5680
Epoch 21/25
229/229 [==============================] - 0s 297us/step - loss: 0.5262 - auc: 0.5692
Epoch 22/25
229/229 [==============================] - 0s 292us/step - loss: 0.5255 - auc: 0.5702
Epoch 23/25
229/229 [==============================] - 0s 299us/step - loss: 0.5248 - auc: 0.5712
Epoch 24/25
229/229 [==============================] - 0s 324us/step - loss: 0.5242 - auc: 0.5722
Epoch 25/25
229/229 [==============================] - 0s 345us/step - loss: 0.5235 - auc: 0.5731
63/63 [==============================] - 0s 269us/step

[I 2024-12-16 22:57:02,636] Trial 5 finished with value: 0.5418168920641405 and parameters: {'epochs': 25, 'batch_size': 35, 'units_layer1': 7, 'units_layer2': 17, 'optimizer': 'sgd', 'learning_rate': 0.00015155116743340453}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

Epoch 1/22
422/422 [==============================] - 0s 358us/step - loss: 0.5806 - auc: 0.4256
Epoch 2/22
422/422 [==============================] - 0s 318us/step - loss: 0.5196 - auc: 0.5365
Epoch 3/22
422/422 [==============================] - 0s 319us/step - loss: 0.4877 - auc: 0.6422
Epoch 4/22
422/422 [==============================] - 0s 321us/step - loss: 0.4664 - auc: 0.6986
Epoch 5/22
422/422 [==============================] - 0s 316us/step - loss: 0.4522 - auc: 0.7294
Epoch 6/22
422/422 [==============================] - 0s 319us/step - loss: 0.4425 - auc: 0.7469
Epoch 7/22
422/422 [==============================] - 0s 317us/step - loss: 0.4357 - auc: 0.7580
Epoch 8/22
422/422 [==============================] - 0s 316us/step - loss: 0.4301 - auc: 0.7664
Epoch 9/22
422/422 [==============================] - 0s 316us/step - loss: 0.4254 - auc: 0.7737
Epoch 10/22
422/422 [==============================] - 0s 316us/step - loss: 0.4211 - auc: 0.7795
Epoch 11/22
422/422 [==============================] - 0s 327us/step - loss: 0.4170 - auc: 0.7849
Epoch 12/22
422/422 [==============================] - 0s 323us/step - loss: 0.4131 - auc: 0.7897
Epoch 13/22
422/422 [==============================] - 0s 318us/step - loss: 0.4091 - auc: 0.7946
Epoch 14/22
422/422 [==============================] - 0s 316us/step - loss: 0.4052 - auc: 0.7990
Epoch 15/22
422/422 [==============================] - 0s 317us/step - loss: 0.4012 - auc: 0.8036
Epoch 16/22
422/422 [==============================] - 0s 315us/step - loss: 0.3973 - auc: 0.8078
Epoch 17/22
422/422 [==============================] - 0s 320us/step - loss: 0.3932 - auc: 0.8119
Epoch 18/22
422/422 [==============================] - 0s 316us/step - loss: 0.3895 - auc: 0.8157
Epoch 19/22
422/422 [==============================] - 0s 317us/step - loss: 0.3857 - auc: 0.8194
Epoch 20/22
422/422 [==============================] - 0s 316us/step - loss: 0.3821 - auc: 0.8230
Epoch 21/22
422/422 [==============================] - 0s 319us/step - loss: 0.3784 - auc: 0.8266
Epoch 22/22
422/422 [==============================] - 0s 318us/step - loss: 0.3754 - auc: 0.8293
63/63 [==============================] - 0s 280us/step

[I 2024-12-16 22:57:05,915] Trial 6 finished with value: 0.8272776070341112 and parameters: {'epochs': 22, 'batch_size': 19, 'units_layer1': 12, 'units_layer2': 19, 'optimizer': 'adam', 'learning_rate': 0.00017550956005959447}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adagrad` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adagrad`.

Epoch 1/11
167/167 [==============================] - 0s 364us/step - loss: 0.6071 - auc: 0.5412
Epoch 2/11
167/167 [==============================] - 0s 352us/step - loss: 0.5134 - auc: 0.6014
Epoch 3/11
167/167 [==============================] - 0s 316us/step - loss: 0.4836 - auc: 0.6680
Epoch 4/11
167/167 [==============================] - 0s 306us/step - loss: 0.4666 - auc: 0.7048
Epoch 5/11
167/167 [==============================] - 0s 298us/step - loss: 0.4548 - auc: 0.7278
Epoch 6/11
167/167 [==============================] - 0s 294us/step - loss: 0.4464 - auc: 0.7409
Epoch 7/11
167/167 [==============================] - 0s 296us/step - loss: 0.4403 - auc: 0.7493
Epoch 8/11
167/167 [==============================] - 0s 303us/step - loss: 0.4358 - auc: 0.7558
Epoch 9/11
167/167 [==============================] - 0s 299us/step - loss: 0.4322 - auc: 0.7602
Epoch 10/11
167/167 [==============================] - 0s 305us/step - loss: 0.4295 - auc: 0.7638
Epoch 11/11
167/167 [==============================] - 0s 300us/step - loss: 0.4273 - auc: 0.7666
63/63 [==============================] - 0s 277us/step

[I 2024-12-16 22:57:06,724] Trial 7 finished with value: 0.776149511282541 and parameters: {'epochs': 11, 'batch_size': 48, 'units_layer1': 16, 'units_layer2': 20, 'optimizer': 'adagrad', 'learning_rate': 0.006350702780943568}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

Epoch 1/10
286/286 [==============================] - 0s 367us/step - loss: 0.4042 - auc: 0.7915
Epoch 2/10
286/286 [==============================] - 0s 325us/step - loss: 0.3561 - auc: 0.8462
Epoch 3/10
286/286 [==============================] - 0s 325us/step - loss: 0.3460 - auc: 0.8555
Epoch 4/10
286/286 [==============================] - 0s 322us/step - loss: 0.3422 - auc: 0.8595
Epoch 5/10
286/286 [==============================] - 0s 331us/step - loss: 0.3366 - auc: 0.8644
Epoch 6/10
286/286 [==============================] - 0s 327us/step - loss: 0.3361 - auc: 0.8657
Epoch 7/10
286/286 [==============================] - 0s 326us/step - loss: 0.3348 - auc: 0.8662
Epoch 8/10
286/286 [==============================] - 0s 321us/step - loss: 0.3332 - auc: 0.8675
Epoch 9/10
286/286 [==============================] - 0s 327us/step - loss: 0.3304 - auc: 0.8691
Epoch 10/10
286/286 [==============================] - 0s 319us/step - loss: 0.3300 - auc: 0.8706
63/63 [==============================] - 0s 270us/step

[I 2024-12-16 22:57:07,945] Trial 8 finished with value: 0.8559467089752056 and parameters: {'epochs': 10, 'batch_size': 28, 'units_layer1': 21, 'units_layer2': 29, 'optimizer': 'adam', 'learning_rate': 0.00500404372800007}. Best is trial 2 with value: 0.8592971905673493.
/var/folders/br/yvkmbr3121n8fd9q6wdmyqfm0000gp/T/ipykernel_30415/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.RMSprop` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.RMSprop`.

Epoch 1/23
174/174 [==============================] - 0s 384us/step - loss: 0.4339 - auc: 0.7575
Epoch 2/23
174/174 [==============================] - 0s 313us/step - loss: 0.3627 - auc: 0.8403
Epoch 3/23
174/174 [==============================] - 0s 318us/step - loss: 0.3497 - auc: 0.8514
Epoch 4/23
174/174 [==============================] - 0s 330us/step - loss: 0.3438 - auc: 0.8578
Epoch 5/23
174/174 [==============================] - 0s 322us/step - loss: 0.3410 - auc: 0.8609
Epoch 6/23
174/174 [==============================] - 0s 320us/step - loss: 0.3389 - auc: 0.8629
Epoch 7/23
174/174 [==============================] - 0s 321us/step - loss: 0.3363 - auc: 0.8653
Epoch 8/23
174/174 [==============================] - 0s 335us/step - loss: 0.3352 - auc: 0.8653
Epoch 9/23
174/174 [==============================] - 0s 324us/step - loss: 0.3323 - auc: 0.8694
Epoch 10/23
174/174 [==============================] - 0s 320us/step - loss: 0.3306 - auc: 0.8701
Epoch 11/23
174/174 [==============================] - 0s 319us/step - loss: 0.3285 - auc: 0.8715
Epoch 12/23
174/174 [==============================] - 0s 317us/step - loss: 0.3273 - auc: 0.8737
Epoch 13/23
174/174 [==============================] - 0s 325us/step - loss: 0.3274 - auc: 0.8744
Epoch 14/23
174/174 [==============================] - 0s 320us/step - loss: 0.3259 - auc: 0.8744
Epoch 15/23
174/174 [==============================] - 0s 320us/step - loss: 0.3235 - auc: 0.8764
Epoch 16/23
174/174 [==============================] - 0s 317us/step - loss: 0.3237 - auc: 0.8762
Epoch 17/23
174/174 [==============================] - 0s 324us/step - loss: 0.3223 - auc: 0.8777
Epoch 18/23
174/174 [==============================] - 0s 334us/step - loss: 0.3214 - auc: 0.8788
Epoch 19/23
174/174 [==============================] - 0s 323us/step - loss: 0.3204 - auc: 0.8803
Epoch 20/23
174/174 [==============================] - 0s 327us/step - loss: 0.3198 - auc: 0.8799
Epoch 21/23
174/174 [==============================] - 0s 323us/step - loss: 0.3186 - auc: 0.8809
Epoch 22/23
174/174 [==============================] - 0s 320us/step - loss: 0.3191 - auc: 0.8805
Epoch 23/23
174/174 [==============================] - 0s 316us/step - loss: 0.3177 - auc: 0.8828
63/63 [==============================] - 0s 275us/step

[I 2024-12-16 22:57:09,505] Trial 9 finished with value: 0.8620000601693292 and parameters: {'epochs': 23, 'batch_size': 46, 'units_layer1': 23, 'units_layer2': 22, 'optimizer': 'rmsprop', 'learning_rate': 0.004002208728285055}. Best is trial 9 with value: 0.8620000601693292.

Best trial: 0.8620000601693292
Best hyperparameters: {'epochs': 23, 'batch_size': 46, 'units_layer1': 23, 'units_layer2': 22, 'optimizer': 'rmsprop', 'learning_rate': 0.004002208728285055}

In [15]:
best_params = study.best_trial.params

best_params

{'epochs': 23,
 'batch_size': 46,
 'units_layer1': 23,
 'units_layer2': 22,
 'optimizer': 'rmsprop',
 'learning_rate': 0.004002208728285055}

In [16]:
# Train the final model with the best hyperparameters

best_model = Sequential()
best_model.add(Dense(units=best_params['units_layer1'], activation='relu'))
best_model.add(Dense(units=best_params['units_layer2'], activation='relu'))
best_model.add(Dense(1, activation='sigmoid'))

In [17]:
if best_params['optimizer'] == 'adam':
    best_optimizer = Adam(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'sgd':
    best_optimizer = SGD(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'rmsprop':
    best_optimizer = RMSprop(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'adagrad':
    best_optimizer = Adagrad(learning_rate=best_params['learning_rate'])

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.RMSprop` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.RMSprop`.

In [18]:
best_model.compile(optimizer=best_optimizer, loss='binary_crossentropy', metrics=['AUC'])

In [19]:
def evaluate(model, X_train, y_train, X_test, y_test):
    
    model.fit(X_train, y_train, epochs=23, batch_size=best_params['batch_size'])
    
    '''Predictions and probabilities for the training set'''
    
    y_train_prob = model.predict(X_train)

    '''Predictions and probabilities for the test set'''
    
    y_test_prob = model.predict(X_test)

    '''Calculate metrics for the training set''' 
    
    roc_train_prob = roc_auc_score(y_train, y_train_prob)
    gini_train_prob = roc_train_prob * 2 - 1
    

    '''Calculate metrics for the test set'''
    
    roc_test_prob = roc_auc_score(y_test, y_test_prob)
    gini_test_prob = roc_test_prob * 2 - 1
    

    results = pd.DataFrame({
        'Dataset': ['Train', 'Test'],
        'Gini': [gini_train_prob * 100, gini_test_prob * 100],
    
    })

    return results

In [20]:
evaluate(best_model, X_train, y_train, X_test, y_test)

Epoch 1/20
174/174 [==============================] - 0s 390us/step - loss: 0.4345 - auc: 0.7555
Epoch 2/20
174/174 [==============================] - 0s 343us/step - loss: 0.3718 - auc: 0.8310
Epoch 3/20
174/174 [==============================] - 0s 365us/step - loss: 0.3506 - auc: 0.8507
Epoch 4/20
174/174 [==============================] - 0s 342us/step - loss: 0.3456 - auc: 0.8561
Epoch 5/20
174/174 [==============================] - 0s 352us/step - loss: 0.3416 - auc: 0.8598
Epoch 6/20
174/174 [==============================] - 0s 359us/step - loss: 0.3365 - auc: 0.8649
Epoch 7/20
174/174 [==============================] - 0s 358us/step - loss: 0.3339 - auc: 0.8667
Epoch 8/20
174/174 [==============================] - 0s 348us/step - loss: 0.3317 - auc: 0.8690
Epoch 9/20
174/174 [==============================] - 0s 347us/step - loss: 0.3278 - auc: 0.8714
Epoch 10/20
174/174 [==============================] - 0s 340us/step - loss: 0.3270 - auc: 0.8725
Epoch 11/20
174/174 [==============================] - 0s 340us/step - loss: 0.3247 - auc: 0.8754
Epoch 12/20
174/174 [==============================] - 0s 339us/step - loss: 0.3227 - auc: 0.8762
Epoch 13/20
174/174 [==============================] - 0s 363us/step - loss: 0.3210 - auc: 0.8794
Epoch 14/20
174/174 [==============================] - 0s 363us/step - loss: 0.3193 - auc: 0.8806
Epoch 15/20
174/174 [==============================] - 0s 333us/step - loss: 0.3176 - auc: 0.8817
Epoch 16/20
174/174 [==============================] - 0s 348us/step - loss: 0.3162 - auc: 0.8827
Epoch 17/20
174/174 [==============================] - 0s 394us/step - loss: 0.3151 - auc: 0.8843
Epoch 18/20
174/174 [==============================] - 0s 358us/step - loss: 0.3141 - auc: 0.8843
Epoch 19/20
174/174 [==============================] - 0s 340us/step - loss: 0.3132 - auc: 0.8849
Epoch 20/20
174/174 [==============================] - 0s 343us/step - loss: 0.3128 - auc: 0.8857
250/250 [==============================] - 0s 253us/step
63/63 [==============================] - 0s 281us/step

  Dataset       Gini
0   Train  79.417689
1    Test  70.045491

## deploy

In [45]:
data = {
    'CreditScore': [600, 750, 680, 720, 590],
    'Age': [40, 35, 50, 29, 45],
    'Tenure': [3, 7, 5, 2, 10],
    'Balance': [60000, 85000, 0, 50000, 120000],
    'NumOfProducts': [2, 1, 2, 3, 1],
    'HasCrCard': [1, 0, 1, 1, 0],
    'IsActiveMember': [1, 0, 1, 1, 0],
    'EstimatedSalary': [50000, 70000, 40000, 80000, 30000],
    'Geography_Germany': [0, 1, 0, 0, 0],
    'Geography_Spain': [0, 0, 1, 0, 0],
    'Gender_Male': [1, 0, 1, 1, 0]
}

# Create a DataFrame
cust = pd.DataFrame(data)

cust

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,600,40,3,60000,2,1,1,50000,0,0,1
1,750,35,7,85000,1,0,0,70000,1,0,0
2,680,50,5,0,2,1,1,40000,0,1,1
3,720,29,2,50000,3,1,1,80000,0,0,1
4,590,45,10,120000,1,0,0,30000,0,0,0

In [46]:
scaler.fit(cust)

scaled = scaler.transform(cust)

df_test_scaled = pd.DataFrame(scaled, columns=cust.columns)

df_test_scaled

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,-1.0677,0.0272,-0.8361,-0.0756,0.2673,0.8165,0.8165,-0.2157,-0.5000,-0.5000,0.8165
1,1.2876,-0.6522,0.5574,0.5542,-1.0690,-1.2247,-1.2247,0.8627,2.0000,-0.5000,-1.2247
2,0.1884,1.3860,-0.1393,-1.5869,0.2673,0.8165,0.8165,-0.7548,-0.5000,2.0000,0.8165
3,0.8165,-1.4675,-1.1844,-0.3275,1.6036,0.8165,0.8165,1.4018,-0.5000,-0.5000,0.8165
4,-1.2247,0.7066,1.6025,1.4358,-1.0690,-1.2247,-1.2247,-1.2940,-0.5000,-0.5000,-1.2247

In [47]:
cust['predicted_churn'] = best_model.predict(df_test_scaled)


cust

1/1 [==============================] - 0s 11ms/step

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male,predicted_churn
0,600,40,3,60000,2,1,1,50000,0,0,1,0.2265
1,750,35,7,85000,1,0,0,70000,1,0,0,0.4541
2,680,50,5,0,2,1,1,40000,0,1,1,0.0374
3,720,29,2,50000,3,1,1,80000,0,0,1,0.0199
4,590,45,10,120000,1,0,0,30000,0,0,0,0.2252